### ISSUE TITLE
Can't find emulator executable

### ISSUE THREAD

**Issue by L0WR1D3Rz** [jackgllghr/PlayniteEmudeck#3]
Hi, I have the latest version of emudeck installed on my GPD Win 4 using windows 11. The Emudeck installation  option I picked was to install on SDCard.
I install the add on, however when I try to launch a yuzu game through playnite it says it can't find the emulator executable. I tried to point it to different directories such as users/emudeck/emulationstation-de/emulators , but also the launchers directory in the sdcard that contains all the ps1 (powershell) files. Nothing works. Is there a step by step guide on how to make it work for emudeck SDCard installation so that I can launch yuzu games via playnite?

**Comment by jackgllghr** [comment]
Hey so I've this same setup in my ROG Ally, so I installed Emudeck to D:/Emulation, so in that folder I have the folders: roms, saves, bios...

Then in the Addon in Playnite in the settings, I just point it to D:/Emulation 👍

I'll see if I can pick up the installed Emudeck path automatically if I get a chance but I'm not sure if that's exposed anywhere

**Comment by L0WR1D3Rz** [comment]
I also tried that. D is my sd card, and it's all with default directories made by emudeck... Even if I point it to that folder it still won't see the emulator executables :(

**Comment by jackgllghr** [comment]
Hmm, I'll take a look with the latest Emudeck, maybe something changed their side. 

All this plugin actually does is set Playnites emulator and auto-scan configurations so if you want to debug you can go into Library > Configure Emulators, and check the entry for yuzu and see if it's pointing to the correct Emudeck script

**Comment by L0WR1D3Rz** [comment]
Thanks. Let me know if it works for you with latest version. If so is there any way for me to wipe all settings and set up from scratch?

**Comment by jackgllghr** [comment]
Yeah so in the Addon Settings (Addons > Addon Settings > General > Emudeck) the Reload Configuration button attempts to do this, but the most bulletproof way is just to go into Library > Configure Emulators and manually delete all the entries there, and do the same in the auto-scan configurations tab

**Comment by L0WR1D3Rz** [comment]
Hey i followed your clear everything steps and it worked! Is it possible to remove the prompt that asks me whether I want switch ryujinx or switch yuzu, and have it immediately launch as yuzu?

**Comment by jackgllghr** [comment]
Glad to hear, I just installed the latest Emudeck, reloaded my Addons configuration and was able to run Super Mario RPG through both Ryujinx and Yuzu just fine too 👍

As for the prompt, this is a Playnite thing, it's where you have multiple "play" scripts for a game, I'm pretty sure you can set a default, but can't remember exactly where the setting is. 

The next thing I'm working on is being able to select what emulators you want to use(rather than including all them) so when that's done you could just disable ryujinx or yuzu for all Switch games, but the reality is that some games work better in one or the other so you'll likely still need to set Ryujinx or Yuzu on a per-game basis.

**Comment by jackgllghr** [comment]
Thanks for using the Addon too and for the feedback, it's greatly appreciated 😊

**Comment by L0WR1D3Rz** [comment]
Thank you for your work! Your plugin solves hours of headache to users!
